### ISSUE TITLE
Vectorize vectorized VFP instructions on host

### ISSUE THREAD

**Issue by MerryMage** [MerryMage/dynarmic#114]
There is no need to write a vectorizer in the backend. 

Tasks: 

* Introduce IR instructions that support vectorization.
* Implement a decomposition pass for backends that don't support vectorization.
* Implement vectorized instructions in x64 backend.

Issues:

* Strict IEEE exception flag bit support may not happen.

**Comment by FernandoS27** [comment]
hmn, you should add decompose to microinstructions and recompose when possible.

**Comment by MerryMage** [comment]
Will not perform this optimisation until actual users of the vector portion of VFP are found.
