### ISSUE TITLE
Hint instructions

### ISSUE THREAD

**Issue by MerryMage** [MerryMage/dynarmic#132]
Do something with hint instructions, since they normally mark busy-wait loops.

Enabling this should be a JIT-time option in `UserConfig`. Options of things one could implement include: Firing a callback to ask the library user what to do next, advancing time to next event, &c.

**Comment by FernandoS27** [comment]
for starters they should generate hints in the IR instead of NOPs, that way we can use passes and context to give them some use.

**Comment by MerryMage** [comment]
Punted decision over to the library users in b2d781da3a497927ac31c8d64c207409485c8c59.
