### ISSUE TITLE
Only builds on x86_64

### ISSUE THREAD

**Issue by jbeich** [MerryMage/dynarmic#35]
For simplicity (system Boost 1.55 here) I'm building as part of Citra with dynarmic updated to git master. Both Clang 3.6 and GCC 5.4 fail at least on FreeBSD i386 9.3/10.1/11.0.

``` c++
In file included from src/backend_x64/abi.cpp:19:
In file included from src/./backend_x64/abi.h:10:
src/./backend_x64/hostloc.h:93:8: fatal error: no type named 'Reg64' in namespace 'Xbyak'
Xbyak::Reg64 HostLocToReg64(HostLoc loc);
~~~~~~~^
```

or with `add_definitions(-DXBYAK64=1)`

```
In file included from src/backend_x64/hostloc.cpp:7:
In file included from src/./backend_x64/hostloc.h:8:
externals/xbyak/xbyak/xbyak.h:1282:54: fatal error: shift count >= width of type [-Wshift-count-overflow]
        static const size_t dummyAddr = (size_t(0x11223344) << 32) | 55667788;
                                                            ^  ~~
```

Note, aarch64 [fails](http://thunderx1.nyi.freebsd.org/data/110arm64-default/423899/logs/errors/citra-s20161007_1.log) with the same error.

**Comment by MerryMage** [comment]
32-bit systems are not (yet?) supported. Code generation currently relies on x64 features like 64-bit registers.

**Comment by MerryMage** [comment]
Update: With 2a1cf94b1c042e3238c48b3b91d1c6d2170ce198, cmake now emits a `FATAL_ERROR` if compiled on a non-amd64 platform.

**Comment by MerryMage** [comment]
@jbeich 
With citra-emu/citra#3352, Citra should build without dynarmic on non-arm64 platforms.

**Comment by MerryMage** [comment]
Closed as x86_64 support only is intentional for now. There are no plans for 32-bit x86 support. AArch64 support is planned.

**Comment by merryhime** [comment]
AArch64 support is likely coming in #697.
