### ISSUE TITLE
ARM64 Dynarec for Citra

### ISSUE THREAD

**Issue by ManiManitasT210** [MerryMage/dynarmic#420]
To clarify: this thread is now dead: https://github.com/libretro/citra/issues/54

Hi.

This is needed in order to have it running at (near) full speed on the following platforms:

Nintendo Switch (through Horizon OS and/or Lakka OS).

Nvidia Shield TV.

Mobile phones/tablets (Android and iOS devices).

Raspberry Pi 3B+.

If needed, a bounty can be created.

https://www.bountysource.com/issues/66791703-arm64-dynarec-for-citra

**Comment by Narugakuruga** [comment]
Why not read [https://github.com/MerryMage/dynarmic/blob/master/README.md](url) ?

**Comment by MerryMage** [comment]
One is being worked on and will be released when it is ready.
