### ISSUE TITLE
Dynarmic in Citra Canary 1309 crashes on certain instructions

### ISSUE THREAD

**Issue by viocar** [MerryMage/dynarmic#484]
I am modifying a 3DS game, and due to some space constraints, I've had to employ some dirty ASM to fit my modifications in. One modification involves using the following instruction:

`STREQD R3, [R0],-LR (opcode FE3F0000)`

This instruction is hit by the PC but will not execute because it very shortly follows a BEQ not taken and flags are not updated before this instruction is hit. When it is hit, I get an assertion failed error in line 148 of dynarmic.cpp in Citra. This does not crash with the JIT off, and it does not crash on hardware.

I also tried (erroneously):

`STRDLS R3, [R0], -LR (opcode FE3F0090)`

which also crashed. Perhaps the problem has to do with the negative link register as the operand? LR's value would have been equivalent to the opcode of the instruction.

**Comment by wwylele** [comment]
iirc the "D" version of LDR and STR can be only used with even-numbered registers. For example R2 is legal, while R3 is not.

**Comment by MerryMage** [comment]
^ It's an undefined instruction in the spec. (Manual section A8.6.201.)

**Comment by viocar** [comment]
I see - I didn't know that D instructions had that restriction. Still, I feel like it shouldn't be causing the entire program to crash if it doesn't crash on hardware, especially since the instruction is not executing due to its predication. Nevertheless, I was able to fix it by changing it to `FE3F0009`, which is `STMEQDB         R0, {R1-SP}` and valid.

**Comment by MerryMage** [comment]
Closed as the intention is for the library user (in this case, Citra) to provide implementation(s) of any unpredictable or undefined instructions as required.
