### ISSUE TITLE
x64: DenormalsAreZero SSE 4.1 compatibility

### ISSUE THREAD

**Issue by Krnlsoft** [MerryMage/dynarmic#511]
Hello, my CPU is an old Q9300 (SSE 4.1),
since the opcode linked below "pcmpgtq" is introduced on SSE 4.2, I need an equivalent one for SSE 4.1, cause I receive the following error:

received signal SIGILL, Illegal instruction.

For what I can understand, I should split the qword and compare the upper and lower dword using "pcmpgtd", but I don't know how to do it with the library.

https://github.com/MerryMage/dynarmic/blob/8d1699ba2db216e569e998ea318d5cde47720e97/src/backend/x64/emit_x64_floating_point.cpp#L99

Not sure if you mind supporting SSE 4.1.
Thanks anyway for your precious time.
Karl

**Comment by MerryMage** [comment]
Hey, thanks very much for your bug report!

We intend on supporting SSSE3 and above, so something like this is certainly a bug.

Please wait for a fix!

**Comment by Krnlsoft** [comment]
No hurry, thanks for your response, if you need me to run any unit test or something else that may help you improve the project, I'm all ears!
Thanks again!

**Comment by MerryMage** [comment]
Pushed e4b9043f.

**Comment by Krnlsoft** [comment]
It works! Thanks
