### ISSUE TITLE
yuzu crashes at boot  in cricket 19

### ISSUE THREAD

**Issue by bukyapavankumar** [MerryMage/dynarmic#514]
providing the log below
[yuzu_log_cricket19.txt](https://github.com/MerryMage/dynarmic/files/4562599/yuzu_log.txt)
feel frree to close if it is not dynarmic related

**Comment by lioncash** [comment]
This just seems like unimplemented functions causing the game crash.

**Comment by bukyapavankumar** [comment]
Oh but I didn't found any unimplemented function errors so posted here anyways
