### ISSUE TITLE
Accurate fallback on unsafe FP optimizations with FMA and AVX

### ISSUE THREAD

**Issue by ReinUsesLisp** [MerryMage/dynarmic#567]
The commit 6bbc53839fbafb23a1be14d2a2c572f16130825f added an unsafe fallback for CPUs without AVX or FMA (depending on the microinstruction). As expected, this improved performance on devices without those instruction sets.

On devices with the named instruction sets an [accurate path](https://github.com/MerryMage/dynarmic/blob/master/src/backend/x64/emit_x64_floating_point.cpp#L825) can still be taken when the unsafe flag is set. I've profiled a commercial game consistently hitting this slow path on one particular scene. There are other performance issues on that scene, although this is the first layer in the profiler.

I can change it to use the unsafe path when the flag is set; but I wanted to ask if this would be a proper solution, before taking action.

**Comment by MerryMage** [comment]
This was intentional for proper NaN handling and handling of the inf/zero case (which, to be fair, most games don't really care about).

If this is a concern one could add a new flag e.g. `OptimizationFlag::Unsafe_InaccurateNaN` for this case.

Done in eeeafaf5fbfb274b44647b6da86db012c622d621.
