### ISSUE TITLE
A32: VMOVL instruction not implemented

### ISSUE THREAD

**Issue by zhkl0228** [MerryMage/dynarmic#598]
Vector Move Long takes each element in a doubleword vector, sign or zero-extends them to twice their original length, and places the results in a quadword vector.

Advanced SIMD
`VMOVL<c>.<dt> <Qd>, <Dm>`

eg: vmovl.u8 q9, d18 => 322AC8F3 : 0xf3c82a32

**Comment by MerryMage** [comment]
VMOVL is a subset of VSHLL functionality, and it appears to be implemented. Please clarify.

**Comment by zhkl0228** [comment]
Thanks for your respond promptly, but also thank you to create this great project
