### ISSUE TITLE
[Question] How to follow memory accesses?

### ISSUE THREAD

**Issue by Kelebek1** [MerryMage/dynarmic#604]
Sorry, I didn't know where else to ask this.

Do you have any tips on trying to follow memory accesses accessed via JIT'd code? I'm attempting to find a decompression routine for a game, and starting by breakpointing the files I want when read in through the yuzu kernel. I then try to breakpoint that memory to see further accesses but quickly run into a dead end. I'm met with code blocks like this:

![Untitled-1](https://user-images.githubusercontent.com/34639600/117463859-03220780-af48-11eb-97f8-1621e150e5fe.png)

It seems to access a certain memory size, byte/word/dword, save it in various places 5 or so times, and then never accesses the memory again. These same blocks seem to be used for anything read by the game, but I have no idea what it's attempting to do. Do you know which part of dynarmic generates these blocks, and do you have any ideas on tracing memory further than that? Or maybe a way to relate these blocks back into the original executable address itself?

Thanks!

**Comment by MerryMage** [comment]
> These same blocks seem to be used for anything read by the game, but I have no idea what it's attempting to do. 

It's reading memory via the emulated page table.

> Do you know which part of dynarmic generates these blocks

[here](https://github.com/MerryMage/dynarmic/blob/5ebe11c329e5f6d378edb8c70dcc69205d1d8b2f/src/backend/x64/a64_emit_x64.cpp#L887).

> and do you have any ideas on tracing memory further than that?

Consider perhaps disabling pagetable access (set conf.page_tables = nullptr over [here](https://github.com/yuzu-emu/yuzu/blob/260b841dc30e642d00cff993276f2d9dc91fe04c/src/core/arm/dynarmic/arm_dynarmic_64.cpp#L154)), and instead hooking the [MemoryRead/Write functions](https://github.com/yuzu-emu/yuzu/blob/260b841dc30e642d00cff993276f2d9dc91fe04c/src/core/arm/dynarmic/arm_dynarmic_64.cpp#L32) instead.

> Or maybe a way to relate these blocks back into the original executable address itself?

We emit x64 -> arm mapping information on Linux in perf format as long as the `PERF_BUILDID_DIR` env var is available.

**Comment by Kelebek1** [comment]
Wow, super quick response. Thank you!
