### ISSUE TITLE
Appveyor CI

### ISSUE THREAD

**Issue by MerryMage** [MerryMage/dynarmic#65]
Breaking the build on Windows is bad probably.

**Comment by FernandoS27** [comment]
-    RUNTIME_FUNCTION* rfuncs = static_cast<RUNTIME_FUNCTION*>(code->alloc(sizeof(RUNTIME_FUNCTION)));
 +    RUNTIME_FUNCTION* rfuncs = static_cast<RUNTIME_FUNCTION*>(code->AllocateFromCodeSpace(sizeof(RUNTIME_FUNCTION)));

you just forgot to rename this. (line 193 unwind_windows.cpp)

**Comment by MerryMage** [comment]
Thinking more longterm than that.

**Comment by MerryMage** [comment]
Closed by 59aeed0b701378a8a784f9fbdcc94380e32417b0.
