### ISSUE TITLE
Integration Tests

### ISSUE THREAD

**Issue by FernandoS27** [MerryMage/dynarmic#79]
Currently we posses a bunch of unit tests for every instruction but there are still things we can't test to it's full effect with ease like instruction integration, optimization passes and quality of generated blocks.

My current idea would be to generate a bunch of linker independant code using C or direct Assembly, generate objects files using GNU's Assembler for the correct target architecture. The ideal test suite would create an stub client that loads the .data sections and the .text sections and does runs on it checking the ending results of both the JIT and the interpreter.

Right now this kind of tests are being made by hand and it's a very tedious work.

**Comment by MerryMage** [comment]
Related is previous work on replacing the current tests altogether: 448fe2fc486d6c456b9e9c36ebd68978afb59397.

**Comment by MerryMage** [comment]
A64 frontend pretty much has this done. Work will be ported to the A32 frontend.
