### ISSUE TITLE
Issues with licensing as GPLv2 or later

### ISSUE THREAD

**Issue by jroweboy** [MerryMage/dynarmic#81]
Similar to https://github.com/citra-emu/citra/issues/1279 the interpreter code is licensed under GPLv2, but several files in dynarmic claim to be licensed under GPLv2 or later. After all of the interpreter fallbacks have been removed, it would be possible to have a release thats actually GPLv3 compatible. 

Related to https://github.com/MerryMage/dynarmic/issues/69

**Comment by MerryMage** [comment]
This library itself doesn't depend on the interpreter in this repository as a fallback, it depends on whatever the user of the library provides via a callback.

The provided interpreter is only used in tests, so the tests are GPLv2 only. The library itself is GPLv2+.

Passing the buck.

**Comment by neobrain** [comment]
This is a test comment - sorry for the spam!

**Comment by neobrain** [comment]
This is another comment for testing.
