### ISSUE TITLE
Optimization: Multiple exits in basic blocks

### ISSUE THREAD

**Issue by MerryMage** [MerryMage/dynarmic#88]
Currently we only allow a single exit in a basic block.

Allowing for multiple exits would allow for longer basic blocks and the generation of better code.

**Requirements:** 

* A revamp/removal of the concept of terminal instructions is required.
* A new IR instruction that conditionally jumps out of a block.

N.B.: These "longer basic blocks" no longer fit the definition of basic blocks, but are rather more like traces.

Edit: Dolphin calls this "conditional continue".

**Comment by FernandoS27** [comment]
hmn a possible way to implement this is building a Control Flow Graph out of the obtained blocks and detect subgraphs. Those subgraphs normaly refer to functions. The blocks on those subgraphs could then be mashed up together and built as position independent code and stored in an AVL tree of functions for ease of caching and linking.

I would suggest looking into: https://github.com/blend2d/b2dpipe/tree/master/src/b2dpipe

**Comment by MerryMage** [comment]
Essentially: Explicit branch instructions. Removing the concept of a terminal microinstruction may also be helpful.

**Comment by MoochMcGee** [comment]
This is necessary for an x86 frontend, which I plan to write at some point.

**Comment by degasus** [comment]
Do you think adding this feature is a good step to get in-block branching? I fear that the merging might be harder than the forking. But in the long term, we might want to support both.

**Comment by marcospampi** [comment]
A solution would be to work on IR modules: each module has an entry block, each block has a terminal construct which could link to others blocks via adjacency lists ( conditional/branching ) or return to dispatcher.

**Comment by MerryMage** [comment]
Closed in preference of proper function analysis.
